# Generated by Django 4.1 on 2023-03-08 14:03

from django.core.management import call_command
from django.db import migrations


def load_test_data(apps, schema_editor):
    call_command("loaddata", "task_manager_db_data.json")


class Migration(migrations.Migration):
    dependencies = [
        ("task_manager", "0001_initial"),
    ]

    operations = [migrations.RunPython(load_test_data)]
